### ISSUE TITLE
png image gets squished vertically

### ISSUE THREAD

**Issue by Bisaloo** [ColinFay/hexmake#1]
Test image:

![colibri_coruscans](https://user-images.githubusercontent.com/10783929/70907374-ff1ae000-2008-11ea-94e5-9caeadcdaa0d.png)

How it looks on the hex sticker:

![Screenshot from 2019-12-16 13-37-06](https://user-images.githubusercontent.com/10783929/70907419-1c4fae80-2009-11ea-8866-2c7631721eb8.png)

**Comment by ColinFay** [comment]
Ok I'm a little bit confused about how to keep the original ratio of the image. 

Documentation specifies that `asp` should be able to do that but it doesn't seem to change anything. 

Filled a SO question: https://stackoverflow.com/questions/59363489/keep-original-image-ratio-in-ggimage

**Comment by ColinFay** [comment]
Hey, 

Can you check the latest version at http://connect.thinkr.fr/hexmake/ and let me know ? 

That seems to be solved

![Screenshot 2019-12-20 at 16 58 05](https://user-images.githubusercontent.com/17936236/71267042-ea608400-2349-11ea-9f8a-0e23bd59c685.png)
